name: npx smoke

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: npx from GitHub (current ref)
        shell: bash
        run: |
          set -euo pipefail
          export HOME="$(mktemp -d)"
          # Limit run time so the stdio server doesn't hang the job
          timeout 5s npx --yes "github:${{ github.repository }}@${{ github.ref_name }}" fastmail-mcp || true



